blogr/models/comment.py
from blogr import db
from datetime import datetime

class Comment(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    body = db.Column(db.Text)
    created_at = db.Column(db.DateTime, default=datetime.utcnow())
    author_id = db.Column(db.Integer, db.ForeignKey("user.id"))
    post_id = db.Column(db.Integer, db.ForeignKey("post.id"))

    def __repr__(self):
        return "<Comment {}>".format(self.body[::20])

blogr/models/post.py
from blogr import db
from datetime import datetime

class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(50))
    body = db.Column(db.Text)
    created_at = db.Column(db.DateTime, default=datetime.utcnow())
    author_id = db.Column(db.Integer, db.ForeignKey("user.id"))
    comments = db.relationship("Comment", backref="post", lazy=True)
    
    def __repr__(self):
        return "<Post {}>".format(self.body)

blogr/models/user.py
from blogr import db, login
from datetime import datetime
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

@login.user_loader
def load_user(id):
    return User.query.get(int(id))

class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    first_name = db.Column(db.String(50))
    last_name = db.Column(db.String(50))
    email = db.Column(db.String(50), unique=True)
    bio = db.Column(db.Text)
    password_hash = db.Column(db.String(128))
    created_at = db.Column(db.DateTime, default=datetime.utcnow())
    comments = db.relationship("Comment", backref="user", lazy=True)
    posts = db.relationship("Post", backref="user", lazy=True)

    def __repr__(self):
        return "<User {} {}>".format(self.first_name, self.last_name)

    def full_name(self):
        return "{} {}".format(self.first_name, self.last_name)
    
    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

blogr/forms/auth.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import ValidationError, DataRequired, Email, EqualTo
from blogr.models.user import User

class RegistrationForm(FlaskForm):
    first_name = StringField("First Name", validators=[DataRequired()])
    last_name = StringField("Last Name", validators=[DataRequired()])
    email = StringField("Email Address", validators=[DataRequired(), Email()])
    password = PasswordField("Password", validators=[DataRequired()])
    password2 = PasswordField("Confirm Password", validators=[DataRequired(), EqualTo("password")])
    submit = SubmitField("Register")

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user is not None:
            raise ValidationError("The email address is attached to an account.")

class LoginForm(FlaskForm):
    email = StringField("Email Address", validators=[DataRequired()])
    password = PasswordField("Password", validators=[DataRequired()])
    remember_me = BooleanField("Remember Me")
    submit = SubmitField("Login")

blogr/forms/comment.py
from flask_wtf import FlaskForm
from wtforms import TextAreaField, SubmitField
from wtforms.validators import DataRequired

class CommentCreationForm(FlaskForm):
    body = TextAreaField(validators=[DataRequired()])
    submit = SubmitField("Add Comment")

blogr/forms/post.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

class PostForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired()])
    body = TextAreaField("Body", validators=[DataRequired()])

class PostCreationForm(PostForm):
    submit = SubmitField("Create Post")

class PostEditForm(PostForm):
    submit = SubmitField("Edit Post")

blogr/__init__.py
from blogr.config import Config
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager

app = Flask(__name__)
app.config.from_object(Config)

db = SQLAlchemy(app)
migrate = Migrate(app, db)
login = LoginManager(app)
login.login_view = "login"

from blogr.views.auth import auth
from blogr.views.post import post

app.register_blueprint(auth, url_prefix="/auth")
app.register_blueprint(post, url_prefix="/posts")

from blogr.views import views

blogr/views/auth.py
from flask import Blueprint, flash, redirect, render_template, url_for
from flask_login import current_user, login_user, logout_user
from blogr import db
from blogr.forms.auth import RegistrationForm, LoginForm
from blogr.models.user import User

auth = Blueprint("auth", __name__)

@auth.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("index"))
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(first_name=form.first_name.data, last_name=form.last_name.data, email=form.email.data)
        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()
        return redirect(url_for("auth.login"))
    return render_template("auth/register.html", form=form)
        

@auth.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("index"))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user is None or not user.check_password(form.password.data):
            flash("Invalid email or password.")
            return redirect(url_for("auth.login"))
        login_user(user, remember=form.remember_me.data)
        return redirect(url_for("index"))
    return render_template("auth/login.html", form=form)

@auth.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("index"))

blogr/views/post.py
from flask import Blueprint, request, redirect, render_template, url_for
from flask_login import login_required, current_user
from blogr import db
from blogr.forms.post import PostCreationForm, PostEditForm
from blogr.forms.comment import CommentCreationForm
from blogr.models.post import Post
from blogr.models.comment import Comment

post = Blueprint("post", __name__)

@post.route("/create", methods=["GET", "POST"])
@login_required
def create_post():
    form = PostCreationForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, body=form.body.data, author_id=current_user.id)
        db.session.add(post)
        db.session.commit()
        return redirect(url_for("index"))
    return render_template("post/create_post.html", form=form)

@post.route("/<int:post_id>", methods=["GET"])
def post_detail(post_id):
    form = CommentCreationForm()
    post = Post.query.filter_by(id=post_id).first_or_404()
    return render_template("post/post_detail.html", post=post, form=form)

@post.route("/<int:post_id>/edit", methods=["GET", "POST"])
def edit_post(post_id):
    form = PostEditForm()
    post = Post.query.filter_by(id=post_id).first_or_404()
    if form.validate_on_submit():
        post.title = form.title.data
        post.body = form.body.data
        db.session.add(post)
        db.session.commit()
        return redirect(url_for("index"))
    form.title.data = post.title
    form.body.data = post.body
    return render_template("post/edit_post.html", form=form)

@post.route("/<int:post_id>/delete", methods=["POST"])
def delete_post(post_id):
    post = Post.query.filter_by(id=post_id).first_or_404()
    db.session.delete(post)
    db.session.commit()
    return redirect(url_for("index")) 

@post.route("/<int:post_id>/comment", methods=["POST"])
@login_required
def create_comment(post_id):
    form = CommentCreationForm()
    if form.validate_on_submit():
        post = Post.query.filter_by(id=post_id).first_or_404()
        comment = Comment(body=form.body.data, post_id=post.id, author_id=current_user.id)
        db.session.add(comment)
        db.session.commit()
    return redirect(url_for("post.post_detail", post_id=post_id))

@post.route("/<int:post_id>/comment/<int:comment_id>", methods=["POST"])
@login_required
def delete_comment(post_id, comment_id):
    comment = Comment.query.filter_by(id=comment_id).first_or_404()
    db.session.delete(comment)
    db.session.commit()
    return redirect(url_for("post.post_detail", post_id=post_id))

blogr/views/views.py
from flask import render_template
from blogr.models.post import Post
from blogr import app

@app.route("/", methods=["GET"])
@app.route("/posts", methods=["GET"])
def index():
    posts = Post.query.all()
    return render_template("post/index.html", posts=posts)

blogr/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <title>Blogr</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{{ url_for('index') }}">Blogr</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-link" href="{{ url_for('index') }}">Home</a>
                {% if current_user.is_anonymous %}
                <a href="{{ url_for('auth.login') }}" class="nav-link">Login</a>
                <a href="{{ url_for('auth.register') }}" class="nav-link">Register</a>
                {% else %}
                <a href="{{ url_for('post.create_post') }}" class="nav-link">Create Post</a>
                <a href="{{ url_for('auth.logout') }}" class="nav-link">Logout</a>
                {% endif %}
            </div>
            </div>
        </div>
    </nav>

    <div class="container">
        {% with messages = get_flashed_messages() %}
            {% if messages %}
            <ul>
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}
        {% endwith %}
    {% block content %}

    {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
</body>
</html>

blogr/templates/post/create_post.html
{% extends "layout.html" %}
{% block content %}
<h2>Create Post</h2>

<form action="" method="post">
    {{ form.hidden_tag() }}
    <p>
        {{ form.title.label }} <br>
        {{ form.title(size=32) }} <br>
        {% for error in form.title.errors %}
        <span class="text-danger">[{{ error }}]</span>
        {% endfor %}
    </p>
    <p>
        {{ form.body.label }} <br>
        {{ form.body(size=32) }} <br>
        {% for error in form.body.errors %}
        <span class="text-danger">[{{ error }}]</span>
        {% endfor %}
    </p>
    <p>{{ form.submit() }}</p>
</form>

{% endblock %}

blogr/templates/post/edit_post.html
{% extends "layout.html" %}
{% block content %}
<h2>Edit Post</h2>

<form action="" method="post">
    {{ form.hidden_tag() }}
    <p>
        {{ form.title.label }} <br>
        {{ form.title(size=32) }} <br>
        {% for error in form.title.errors %}
        <span class="text-danger">[{{ error }}]</span>
        {% endfor %}
    </p>
    <p>
        {{ form.body.label }} <br>
        {{ form.body(size=32) }} <br>
        {% for error in form.body.errors %}
        <span class="text-danger">[{{ error }}]</span>
        {% endfor %}
    </p>
    <p>{{ form.submit() }}</p>
</form>

{% endblock %}

blogr/templates/post/index.html
{% extends "layout.html" %}
{% block content %}
<h2>Posts</h2>

{% for post in posts %}
    <div class="card card-body">
        <h5 class="card-title">
            <a href="{{ url_for('post.post_detail', post_id=post.id) }}">{{ post.title }}</a></h5>
        <small class="text-muted">{{ post.created_at }}</small>
        <p class="card-body">{{ post.body }}</p>
    </div>
{% endfor %}
{% endblock %}

blogr/templates/post/post_detail.html
{% extends "layout.html" %}
{% block content %}
<h2>{{ post.title }}</h2>
<small class="text-muted">{{ post.created_at }} by {{ post.user.full_name() }} </small>
<p>{{ post.body }}</p>

<div class="btn-group">
    <form action="{{ url_for('post.edit_post', post_id=post.id) }}" method="get">
        <button type="submit" class="btn btn-primary">Edit</button>
    </form>

    <form action="{{ url_for('post.delete_post', post_id=post.id) }}" method="post">
        <button type="submit" class="btn btn-danger">Delete</button>
    </form>
</div>

<hr>

<h3>Comments</h3>
<form action="{{ url_for('post.create_comment', post_id=post.id) }}" method="post">
    {{ form.hidden_tag() }}
    <p>
        {{ form.body(size=32) }} <br>
        {% for error in form.body.errors %}
        <span class="text-danger">[{{ error }}]</span>
        {% endfor %}
    </p>
    <p>{{ form.submit() }}</p>
</form>
<hr>
{% for comment in post.comments %}
    <div class="card card-body">
        <p>{{ comment.body }}</p>
        <small class="text-muted">{{ comment.created_at }} by {{ comment.user.full_name() }} </small>
        <form action="{{ url_for('post.delete_comment', post_id=post.id, comment_id=comment.id) }}" method="post">
            <button type="submit" class="btn btn-danger">Delete</button>
        </form>
    </div>
{% endfor %}
{% endblock %}